#!/usr/bin/env node
// CYN-785 (CYN-768 P0) — conformance/version-probe gate.
//
// Two kinds of checks, deliberately separated:
//   1. STATIC assertions on the plugin package itself (always run, exit
//      non-zero on failure — this is the usable CI-safe gate).
//   2. Best-effort DETECTION of the installed Claude Code / Codex CLI
//      versions + a printed checklist of RUNTIME mechanics (headersHelper
//      401-retry, Codex url-MCP no-bearer-refresh, trusted-dir,
//      project_doc_max_bytes=32768) that must be confirmed by hand against
//      those versions — the full runtime probe is the P6 bake, not this
//      script. Detection NEVER fails the gate; an absent CLI just prints
//      "not detected" and moves on.
//
// Zero deps — Node built-ins only.

import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { buildProjectMcpJson } from '../lib/connect.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = join(__dirname, '..');
const REPO_ROOT = join(PLUGIN_ROOT, '..', '..');

// ---------------------------------------------------------------------------
// Static assertions
// ---------------------------------------------------------------------------

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

/** Asserts no `${VAR}`-style Authorization header anywhere in an .mcp.json
 * SHAPE (either an already-parsed object, or a path to a JSON file) —
 * .mcp.json headers expand ONCE at parse-time (a static snapshot), so a
 * re-minting token can never live there. The proxy injects the Bearer
 * server-side instead. Takes a shape rather than a fixed path because this
 * plugin ships NO plugin-root .mcp.json (see FIX 1 / README "Why there is no
 * plugin-root MCP server") — the only .mcp.json this plugin ever produces is
 * the per-dir project file generated by lib/connect.mjs buildProjectMcpJson,
 * so the gate must validate THAT shape, not a static file. */
export function assertNoTemplatedAuthHeader(mcpJsonOrPath) {
  const mcpJson = typeof mcpJsonOrPath === 'string' ? readJson(mcpJsonOrPath) : mcpJsonOrPath;
  const servers = mcpJson.mcpServers || {};
  for (const [name, server] of Object.entries(servers)) {
    const headers = server.headers || {};
    for (const [headerName, value] of Object.entries(headers)) {
      if (/^authorization$/i.test(headerName) && /\$\{[^}]+\}/.test(String(value))) {
        throw new Error(
          `.mcp.json server "${name}" has a templated Authorization header ("${value}") — ` +
            'these expand once at parse-time and cannot carry a re-minting token. Use the loopback proxy instead.'
        );
      }
    }
  }
  return true;
}

/** Component dirs (commands/ skills/ hooks/) must live at the plugin ROOT,
 * never nested under .claude-plugin/ — per the verified Claude Code plugin
 * anatomy (the published operator contract
 * Theme 1). */
export function assertComponentDirsAtRoot(pluginRoot) {
  const claudePluginDir = join(pluginRoot, '.claude-plugin');
  const forbidden = ['commands', 'skills', 'hooks', 'agents'];
  for (const name of forbidden) {
    const nested = join(claudePluginDir, name);
    if (existsSync(nested)) {
      throw new Error(
        `Found "${name}/" nested under .claude-plugin/ — component directories must live at the plugin root.`
      );
    }
  }
  return true;
}

/** marketplace.json's plugin name must exactly match plugin.json's name
 * (marketplace names are immutable; a rename needs an explicit `renames` map,
 * not a silent divergence between the two manifests). */
export function assertMarketplaceNameMatchesPlugin(pluginJsonPath, marketplaceJsonPath) {
  const pluginJson = readJson(pluginJsonPath);
  const marketplaceJson = readJson(marketplaceJsonPath);
  const entry = (marketplaceJson.plugins || []).find((p) => p.source === './' || p.name === pluginJson.name);
  if (!entry) {
    throw new Error(`marketplace.json has no entry for plugin "${pluginJson.name}"`);
  }
  if (entry.name !== pluginJson.name) {
    throw new Error(
      `marketplace.json plugin name "${entry.name}" does not match plugin.json name "${pluginJson.name}"`
    );
  }
  if (!Object.prototype.hasOwnProperty.call(marketplaceJson, 'renames')) {
    throw new Error('marketplace.json is missing the `renames` map (required even if empty {})');
  }
  return true;
}

/** The packaged proxy must be byte-identical to the single source of record —
 * enforced here too (not just in the test suite) so `version-probe` alone is
 * a complete conformance gate. */
export function assertProxyByteIdentical(sourcePath, copyPath) {
  const source = readFileSync(sourcePath);
  const copy = readFileSync(copyPath);
  if (!source.equals(copy)) {
    throw new Error(
      `${copyPath} has DRIFTED from ${sourcePath} — run scripts/build-copy-proxy.mjs to re-sync.`
    );
  }
  return true;
}

function runStaticAssertions() {
  const checks = [
    ['no plugin-root .mcp.json (MCP server is provisioned per-dir by /cynap-connect only)', () => {
      if (existsSync(join(PLUGIN_ROOT, '.mcp.json'))) {
        throw new Error(
          'the plugin package/.mcp.json exists — a plugin-root MCP server dedupes by ' +
            'ENDPOINT (not name) per the live Claude Code docs, so a fixed-port plugin-root server ' +
            'collides with the per-dir ephemeral-port servers /cynap-connect generates. The MCP ' +
            'server must be provisioned ONLY by the per-dir project .mcp.json.'
        );
      }
    }],
    ['generated per-dir .mcp.json (buildProjectMcpJson) has no templated Authorization header', () =>
      assertNoTemplatedAuthHeader(buildProjectMcpJson({ port: 12345 }))],
    ['component dirs at plugin root (not under .claude-plugin/)', () =>
      assertComponentDirsAtRoot(PLUGIN_ROOT)],
    ['projected-mirror marketplace manifest at .claude-plugin/marketplace.json (where `claude plugin marketplace add` finds it)', () => {
      if (!existsSync(join(PLUGIN_ROOT, '.claude-plugin', 'marketplace.json'))) {
        throw new Error(
          'no .claude-plugin/marketplace.json here. This is expected ONLY when this script runs from the ' +
            'private monorepo SOURCE tree, which ships no installable marketplace by design (CYN-1959) — ' +
            'local development loads the source directly from its plugin directory. ' +
            'In the PUBLISHED public mirror this file is always present: it is GENERATED by ' +
            'mirror-projection.mjs generatePublicMarketplace on every publish, never hand-authored, and ' +
            '`claude plugin marketplace add <dir>` looks ONLY at .claude-plugin/marketplace.json — a ' +
            'package-root copy fails with "Marketplace file not found" (verified live against Claude Code ' +
            '2.1.201). If you installed this plugin from the mirror and are seeing this, the release is broken.'
        );
      }
      if (existsSync(join(PLUGIN_ROOT, 'marketplace.json'))) {
        throw new Error(
          'a STALE package-root marketplace.json exists alongside .claude-plugin/marketplace.json — delete ' +
            'the root copy (single source of record; the root copy is invisible to `marketplace add`).'
        );
      }
    }],
    ['projected-mirror marketplace.json name matches plugin.json + carries renames map', () =>
      assertMarketplaceNameMatchesPlugin(
        join(PLUGIN_ROOT, '.claude-plugin', 'plugin.json'),
        join(PLUGIN_ROOT, '.claude-plugin', 'marketplace.json')
      )],
    ['bin/operator-proxy.mjs parity check — not applicable in the public mirror (this repo IS the source of record; the private-monorepo build-copy parity gate lives upstream)', () => {}],
  ];

  let failed = false;
  for (const [label, fn] of checks) {
    try {
      fn();
      process.stdout.write(`[version-probe] PASS  ${label}\n`);
    } catch (err) {
      failed = true;
      process.stdout.write(`[version-probe] FAIL  ${label}\n`);
      process.stdout.write(`  ${err instanceof Error ? err.message : String(err)}\n`);
    }
  }
  return !failed;
}

// ---------------------------------------------------------------------------
// Best-effort CLI version detection (never fails the gate)
// ---------------------------------------------------------------------------

function detectCliVersion(bin) {
  try {
    const out = execFileSync(bin, ['--version'], { encoding: 'utf8', timeout: 5000 }).trim();
    return out;
  } catch {
    return null;
  }
}

function bestEffortPluginValidate() {
  try {
    execFileSync('claude', ['--version'], { timeout: 5000 });
  } catch {
    return null; // claude CLI not detected — skip
  }
  try {
    const out = execFileSync('claude', ['plugin', 'validate', PLUGIN_ROOT], {
      encoding: 'utf8',
      timeout: 15000,
    });
    return { ran: true, output: out.trim() };
  } catch (err) {
    // `claude plugin validate` may not exist on this version, or may exit
    // non-zero for reasons unrelated to our static checks — best-effort only.
    return { ran: false, output: err instanceof Error ? err.message : String(err) };
  }
}

function printRuntimeChecklist() {
  const claudeVersion = detectCliVersion('claude');
  const codexVersion = detectCliVersion('codex');
  process.stdout.write('\n[version-probe] Installed CLI versions (best-effort detection):\n');
  process.stdout.write(`  claude: ${claudeVersion ?? 'not detected'}\n`);
  process.stdout.write(`  codex:  ${codexVersion ?? 'not detected'}\n`);

  const validate = bestEffortPluginValidate();
  if (validate) {
    process.stdout.write(
      `\n[version-probe] claude plugin validate: ${validate.ran ? 'ran' : 'unavailable/errored'}\n`
    );
    if (validate.output) {
      process.stdout.write(`  ${validate.output.split('\n').join('\n  ')}\n`);
    }
  } else {
    process.stdout.write('\n[version-probe] claude CLI not detected — skipping `claude plugin validate`.\n');
  }

  process.stdout.write(
    '\n[version-probe] RUNTIME mechanics to confirm by hand against the versions above ' +
      '(documented manual checks — the full runtime probe is the P6 bake):\n' +
      '  [ ] the per-dir project .mcp.json /cynap-connect writes auto-starts its MCP server on plugin/project load\n' +
      '  [ ] ${CLAUDE_PLUGIN_ROOT} resolves to this plugin directory at runtime\n' +
      '  [ ] headersHelper reconnects + retries once on 401/403 (proxy still owns proactive re-mint)\n' +
      '  [ ] Codex config.toml [mcp_servers].url loads this server with NO bearer refresh\n' +
      '  [ ] Codex trusted-dir requirement is satisfied for the connect working directory\n' +
      '  [ ] Codex AGENTS.md project_doc_max_bytes cap is 32768 (unchanged)\n'
  );
}

function main() {
  const staticOk = runStaticAssertions();
  printRuntimeChecklist();
  if (!staticOk) {
    process.stderr.write('\n[version-probe] FAILED — one or more static assertions did not hold.\n');
    process.exit(1);
  }
  process.stdout.write('\n[version-probe] All static assertions passed.\n');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
